language: php
php:
  - '7.2'
  - '7.3'
before_install:
  - sudo apt-get -qq update
  - yes | pecl install imagick
  - sudo apt-get install -y ghostscript
  - travis_retry composer self-update
script:
- phpunit --configuration phpunit.xml
- php coverage-checker.php tests/logs/clover.xml 85
