language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
before_script:
  - printf "\n" | pecl install imagick
script:
- phpunit --configuration phpunit-utils.xml
- phpunit --configuration phpunit-api.xml
- php coverage-checker.php tests/logs/clover.xml 95
