language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'
before_script:
   - pear config-set preferred_state beta
   - pecl channel-update pecl.php.net
   - yes | pecl install imagick
script:
- phpunit --configuration phpunit.xml
- php coverage-checker.php tests/logs/clover.xml 95
