swagger: '2.0'
info:
  version: '0.1.4'
  title: mobilecms content api
  description: ''
host: localhost
basePath: /api/v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  '/upload/{type}/{id}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
      - name: id
        in: path
        required: true
        type: string
    post:
      operationId: POST_upload-type-id
      summary: upload
      tags:
        - Basic File
        - File
      consumes:
        - application/octet-stream
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        default:
          description: ''
  '/download/{type}/{id}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
      - name: id
        in: path
        required: true
        type: string
    post:
      operationId: POST_download-type-id
      summary: sync
      tags:
        - Basic File
        - File
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        default:
          description: ''
  '/delete/{type}/{id}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
      - name: id
        in: path
        required: true
        type: string
    delete:
      operationId: DELETE_delete-type-id
      summary: delete file
      tags:
        - Basic File
        - File
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        default:
          description: ''
  '/basicupload/{type}/{id}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GET_basicupload-type-id
      summary: get files descriptions
      tags:
        - Basic File
        - File
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        default:
          description: ''
  '/content/{type}/{id}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
      - name: id
        in: path
        required: true
        type: string
    get:
      operationId: GET-content
      summary: Get content
      tags:
        - Content
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/article'
    delete:
      operationId: DELETE-content
      summary: Delete content
      tags:
        - Contents
        - Content
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '204':
          description: ''
    put:
      operationId: PUT-content
      summary: Update content
      tags:
        - Contents
        - Content
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '200':
          description: ''
          schema:
            type: object
  '/content/{type}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
    post:
      operationId: POST-content
      summary: Create content
      tags:
        - Contents
        - Content
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '201':
          description: ''
          schema:
            type: object
    get:
      operationId: LIST-contents
      summary: List contents
      tags:
        - Contents
        - Content
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/article'
  '/index/{type}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
    post:
      operationId: POST-index
      summary: Create index
      tags:
        - Indices
        - Index
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '201':
          description: ''
          schema:
            type: object
    get:
      operationId: LIST-indices
      summary: List indices
      tags:
        - Indices
        - Index
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '200':
          description: ''
          schema:
            type: object
            properties:
              '': {}
    put:
      operationId: PUT-index
      summary: Update index
      tags:
        - Indices
        - Index
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/index'
  '/metadata/{type}':
    parameters:
      - name: type
        in: path
        required: true
        type: string
    get:
      operationId: LIST-metadatas
      summary: List metadatas
      tags:
        - Metadatas
        - Metadata
      parameters:
        - $ref: '#/parameters/trait:jwt:Bearer'
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/metadata'
parameters:
  'trait:jwt:Bearer':
    name: Bearer
    in: header
    type: string
definitions:
  index:
    title: Index
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      activity:
        type: string
      title:
        type: string
    required:
      - id
      - title
    example:
      id: sample if
      date: '2017-08-26'
      activity: tennis
      title: some seminar
  link:
    title: Link
    type: object
    properties:
      url:
        type: string
      width:
        type: string
      height:
        type: string
      title:
        type: string
      description:
        type: string
      thumbnails:
        type: array
        items:
          type: object
          properties:
            width:
              type: string
            height:
              type: string
            url:
              type: string
    required:
      - url
    example:
      url: file.jpg
      width: 320px
      height: 200px
      title: file
      description: ''
      thumbnails:
        - width: 320px
          height: 200px
          url: file-320.jpg
  article:
    title: Article
    type: object
    properties:
      id:
        type: string
      date:
        type: string
      enddate:
        type: string
      activity:
        type: string
      title:
        type: string
      organization:
        type: string
      description:
        type: string
      location:
        type: string
      url:
        type: string
      images:
        type: array
        items:
          $ref: '#/definitions/link'
      attachments:
        type: array
        items:
          $ref: '#/definitions/link'
      media:
        type: array
        items:
          $ref: '#/definitions/link'
    example:
      id: test
      date: '2017-08-16'
      enddate: '2017-08-17'
      activity: tennis
      title: test
      organization: foobar
      description: aaaaaaaaaaaaaaaaaaaaaaaa
      location: ...
      url: ''
      images: []
      attachments: []
      media:
        - title: Imprimer.pdf
          url: Imprimer.pdf
          size: 217771
          mimetype: application/pdf
        - title: Inter-iaido-Centre-et-Ouest- 2016-2017.pdf
          url: Inter-iaido-Centre-et-Ouest- 2016-2017.pdf
          size: 325203
          mimetype: application/pdf
        - title: activitya-mobile.jpg
          url: activitya-mobile.jpg
          size: 3272
          mimetype: image/jpeg
        - title: lorem ipsum.pdf
          url: lorem ipsum.pdf
          size: 24612
          mimetype: application/pdf
        - title: banner-old.jpg
          url: banner-old.jpg
          size: 33390
          mimetype: image/jpeg
  metadata:
    title: Metadata
    type: object
    properties:
      name:
        type: string
      primary:
        type: string
      type:
        type: string
      editor:
        type: string
      choices:
        type: array
        items:
          type: string
    example:
      name: activity
      primary: 'false'
      type: text
      editor: choice
      choices:
        - tennis
        - golf
